### ISSUE TITLE
java.net down: where to download binaries?

### ISSUE THREAD

**Issue by russellhoff** [javaee/metro#34]
As of 28th april 2017, java.net site is down. I need to set up an environment, which needs metro stack installed. Where do I download them from?

**Comment by lukasj** [comment]
released versions are in maven central, see https://repo1.maven.org/maven2/org/glassfish/metro/metro-standalone/

**Comment by m0mus** [comment]
https://maven.java.net/content/repositories/releases//org/glassfish/metro/metro-standalone/2.3.1/metro-standalone-2.3.1.zip

**Comment by brunoborges** [comment]
Can the `README.md` have a Maven section documenting the latest version available on central, with the <dependency> code snippet?

**Comment by russellhoff** [comment]
Thank you so much.
