### ISSUE TITLE
Please update official page as it says latest version is 2.3.1

### ISSUE THREAD

**Issue by smolnij** [javaee/metro#48]
The official web page here https://javaee.github.io/metro/
says 
Latest Version
Metro 2.3.1

And link leads to 2.3.1 download page, but latest version currently is 2.4.2 ? 

Thanks

**Comment by lukasj** [comment]
the latest one - 2.4.2 - comes from Eclipse Foundation and is hosted in 'eclipse-ee4j' repos, everything older, ie this,  remains under 'javaee'

**Comment by smolnij** [comment]
oh, sorry my bad.
